[project]
drom-version = "0.1"

[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
ci-systems = ["ubuntu-latest"]
copyright = "OCamlPro SAS"
edition = "4.10.0"
github-organization = "ocamlpro"
license = "LGPL2"
min-edition = "4.08.0"
name = "freeton_wallet"
version = "0.3.1"

# synopsis if different from project synopsis
synopsis = "The 'ft' tool is a multi-account terminal wallet for the Free TON blockchain (meta-package)"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]

# description if different from project description
description = """The 'ft' tool is a multi-account terminal wallet for Free TON users and developers. It implements account creation/queries, contract deployments and calls, and inspection of blockchain state. It is the swissknife of Free TON.

The FreeTON blockchain is the open-source version of the Telegram Open
Network. FreeTON is one of the only blockchains with dynamic sharding
for unlimited scalability and immediate finality for real-time
applications. It also uses Proof-of-Stake with delegation through
smart contracts. Smart contracts are written in dialects of Solidity
and C++ with asynchonous external calls.
"""

[project]
skip = [ "sphinx/index.rst", "sphinx/install.rst", "sphinx/conf.py", "sphinx/about.rst" , "dune", "@test" ]

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
opam-repo = "git+https://github.com/OCamlPro/ocp-opam-repository"

[[package]]
dir = "src/freeton_wallet"
# edit 'src/freeton_wallet/package.toml' for package-specific options

[[package]]
dir = "src/freeton_wallet_lib"
# edit 'src/freeton_wallet_lib/package.toml' for package-specific options

[[package]]
dir = "src/ft"
# edit 'src/ft/package.toml' for package-specific options


[[package]]
dir = "src/freeton_crawler_lib"
# edit 'src/freeton_crawler_lib/package.toml' for package-specific options

[[package]]
dir = "src/freeton_crawler_db"
# edit 'src/freeton_crawler_db/package.toml' for package-specific options

[[package]]
dir = "src/freeton_crawler_updater"
# edit 'src/freeton_crawler_updater/package.toml' for package-specific options

[[package]]
dir = "src/freeton_crawler_db_versions"
# edit 'src/freeton_crawler_db_versions/package.toml' for package-specific options
